import { Inter, Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/navbar";
import Footer from "@/components/layout/footer";

const inter = Inter({ subsets: ["latin"]});
const nunito = Nunito({
  weight: ['600', '700', '800'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-nunito'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={ inter.className }>
      <body className="overflow-x-hidden">
       <Navbar/>
      {children}
      <Footer/>
      </body>

    </html>
  );
}
